name: "Label PR"

on:
  pull_request_target:

jobs:
  labels:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kaocher82'
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
